version: 2.1

orbs:
  node: circleci/node@4.1.0

jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: npm install
      - run:
          name: Test
          command: npm test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build