version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  build:
    docker:
      - image: cimg/node:lts
    resource_class: medium
    steps:
      - checkout
      - run: yarn install
      - run:
          name: Test
          command: yarn test

workflows:
  version: 2
  build-and-test:
    jobs:
      - build